version: '3'

services: 
    
  # Create backend container
  backend: 
  # Create backend container
    build: ./Backend/quentn # path to dockerfile
    ports: 
      - "8080:8080"
    container_name: backend-docker
    restart: always
    
  postgres: 
    image: postgres
    ports:
      - "5432:5432"
    container_name: postgres-docker
    environment:
      - POSTGRES_PASSWORD=Jackson@0123
      - POSTGRES_USER=postgres
    restart: always
    volumes: 
      - ./db:/var/lib/postgresql/data
      # - ./pgstrapi_temp.sql:/var/lib/postgresql/pgstrapi_temp.sql
  
  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: nico.developer.95@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Jackson@0123
    ports:
      - "16543:80"
    depends_on:
      - postgres


