version: '3'

services: 

  postgres: 
    image: postgres:15.1-alpine
    ports:
      - "5432:5432"
    container_name: postgres-docker
    environment:
      - POSTGRES_PASSWORD=Jackson@0123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=quentn
    restart: always
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
  
  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: nico.developer.95@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Jackson@0123
    ports:
      - "16543:80"
    depends_on:
      - postgres
