version: '3'

services: 
  
  # Create backend container
  backend: 
  # Create backend container
    network_mode: host
    build: ./Backend/quentn # path to dockerfile
    ports: 
      - "8080:8080"
    container_name: backend-docker
    restart: always
    
  postgres: 
    network_mode: host
    image: postgres
    ports:
      - "5432:5432"
    container_name: postgres-docker
    environment:
      - POSTGRES_PASSWORD=Jackson@0123
      - POSTGRES_USER=postgres
    restart: always
    volumes: 
      # - ./db:/var/lib/postgresql/data
      - ./pgstrapi_temp.sql:/docker-entrypoint-initdb.d/pgstrapi_temp.sql
